version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Tokyo
    groups:
      aws-sdk-go-v2:
        patterns:
          - "github.com/aws/aws-sdk-go-v2*"
          - "github.com/aws/smithy-go*"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      timezone: Asia/Tokyo
    labels:
      - "dependencies"
      - "github-actions"
