version: 2
jobs:
  build:
    working_directory: /go/src/github.com/youyo/awslogin
    docker:
      - image: golang:1.9
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p ${TEST_RESULTS}
      - run:
          name: Dependency
          command: |
            make setup
            make deps
      - run:
          name: Test
          command: |
            make test | go-junit-report > ${TEST_RESULTS}/go-test-report.xml
      - store_test_results:
          path: ${TEST_RESULTS}
      - run:
          name: Release
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              make build
              make release
            else
              echo "Not master branch."
            fi
