workflows:
  version: 2
  main:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: master

defaults: &defaults
  working_directory: /go/src/github.com/youyo/awslogin
  docker:
    - image: circleci/golang:1

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: mkdir -p /tmp/test-results
      - run:
          name: Dependency
          command: |
            make setup
            make deps
      - run:
          name: Test
          command: |
            trap "go-junit-report </tmp/test-results/go-test.out > /tmp/test-results/go-test-report.xml" EXIT
            make test | tee /tmp/test-results/go-test.out
      - run:
          name: Build
          command: |
            make build
      - store_test_results:
          path: /tmp/test-results
  release:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Dependency
          command: |
            make setup
            make deps
      - run:
          name: Build
          command: |
            make build
      - run:
          name: Release
          command: |
            make release
      - run:
          name: Update Homebrew
          command: |
            make update-homebrew
